Controllers/PresupuestosController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tl2_tp6_2024_MaguiNavarro.Models;
namespace tl2_tp6_2024_MaguiNavarro.Controllers;

public class PresupuestosController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private PresupuestoRepository presRep;

    public PresupuestosController(ILogger<HomeController> logger)
    {
        _logger = logger;
        presRep = new PresupuestoRepository();
    }

    [HttpGet]
    public IActionResult Listar()
    {
        return View(presRep.GetPresupuestos());
    }

    [HttpGet]
    public IActionResult Crear()
    {
        return View(new Presupuesto());
    }

    [HttpPost]
    public IActionResult Crear(Presupuesto presupuesto)
    {
        presupuesto.FechaCreacion = DateTime.Now;
        presRep.create(presupuesto);
        return RedirectToAction("Listar");
    }

    [HttpGet]
    public IActionResult AsignarProducto(int id)
    {
        var presupuesto = presRep.GetPresupuesto(id);
        return View(presupuesto);
    }

    [HttpPost]
    public IActionResult AsignarProducto(int id, int idProducto, int cantidad)
    {   
        presRep.agregarDetalle(id, idProducto, cantidad);
        return RedirectToAction("Listar");
    }

    [HttpGet]
    public IActionResult Modificar(int id)
    {
        var presupuesto = presRep.GetPresupuesto(id); //Me muestra solo el form vacio
        return View(presupuesto);
    }

    [HttpPost]
    public IActionResult Modificar(Presupuesto presupuestoVista)   // Aca reciben 
    {
        var presupuesto = presRep.GetPresupuesto(presupuestoVista.IdPresupuesto);

        presupuesto.Cliente.ClienteId = presupuestoVista.Cliente.ClienteId;
        presupuesto.FechaCreacion = presupuestoVista.FechaCreacion;
        presRep.modificar(presupuesto);

        return RedirectToAction("Listar");
    }

    [HttpGet]
    public IActionResult Eliminar(int id)
    {
        var presupuesto = presRep.GetPresupuesto(id);
        return View(presupuesto);
    }

    [HttpPost]
    public IActionResult EliminarConfirm(int id)
    {
        presRep.delete(id);
        return RedirectToAction("Listar");
    }



    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using tl2_tp6_2024_MaguiNavarro.Models;
namespace tl2_tp6_2024_MaguiNavarro.Controllers;

public class ProductosController : Controller
{
  private readonly ILogger<HomeController> _logger;
    private ProductosRepository prodRep;

    public ProductosController(ILogger<HomeController> logger)
    {
        _logger = logger;
        prodRep = new ProductosRepository();
    }

    public IActionResult Listar()
    {
        return View(prodRep.ListarProductos());
    }

    [HttpGet]
    public IActionResult Crear()
    {
        return View(new Producto());
    }

    [HttpPost]
    public IActionResult Crear(Producto producto)
    {
        prodRep.Create(producto);
        return RedirectToAction("Listar");
    } 

    [HttpGet]
    public IActionResult Modificar(int idProd)
    {
        var producto = prodRep.GetProducto(idProd);
        return View(producto);
    }

    [HttpPost]
    public IActionResult Modificar(Producto productoView)
    {
        var producto = prodRep.GetProducto(productoView.IdProducto);

        producto.Descripcion = productoView.Descripcion;
        producto.Precio = productoView.Precio;

        prodRep.Update(producto);

        return RedirectToAction("Listar");
    }

    [HttpGet]
    public IActionResult Eliminar(int idProd)
    {
        var producto = prodRep.GetProducto(idProd);
        return View(producto);
    }

    [HttpPost]
    public IActionResult EliminarConfirm(int idProd)
    {    
        prodRep.delete(idProd);
        return RedirectToAction("Listar");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

 }

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - tl2_tp6_2024_MaguiNavarro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/tl2_tp6_2024_MaguiNavarro.styles.css" asp-append-version="true" />

</head>
<body>
   
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-red border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Navarro</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Listar">Productos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Presupuestos" asp-action="Listar">Presupuestos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - tl2_tp6_2024_MaguiNavarro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>